name: Run Lighthouse via Node.js

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install lighthouse chrome-launcher

      - name: Run Lighthouse script
        run: node scripts/run-lighthouse.js

      - name: Upload report artifacts
        uses: actions/upload-artifact@v3
        with:
          name: lighthouse-report
          path: report/
